name: audienzz_sdk_flutter
description: "A Flutter plugin that integrates Audienzz Mobile Advertising SDK for easy implementation of advanced ad solutions"
version: 0.0.3
homepage: https://audienzz.com/
repository: https://github.com/audienzz/audienzz-flutter-sdk
issue_tracker: https://github.com/audienzz/audienzz-flutter-sdk/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  collection: ^1.18.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_lints: 5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.audienzz.audienzz_sdk_flutter
        pluginClass: AudienzzSdkFlutterPlugin
      ios:
        pluginClass: AudienzzSdkFlutterPlugin